apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Program Files\Kompose\kompose.exe convert -f docker-compose.yml
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: backend
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: backend
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Program Files\Kompose\kompose.exe convert -f docker-compose.yml
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: backend
    spec:
      containers:
        - image: backend
          livenessProbe:
            exec:
              command:
                - curl -f http://localhost:8888 || exit 1
            failureThreshold: 5
            periodSeconds: 10
            timeoutSeconds: 5
          name: backend
          ports:
            - containerPort: 8888
              protocol: TCP
      restartPolicy: Always
