# Use an official Python runtime as a parent image
FROM python:3.8-slim

# Set the working directory in the container
WORKDIR /app

# Copy the application code to the container
COPY middleware/ /app

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r /app/requirements.txt

# Expose port 5000 for the Flask app
EXPOSE 5000

# Run the Flask application directly
CMD ["flask", "run", "--host=0.0.0.0", "--port=5000"]
